apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: master-es
spec:
   serviceName: elasticsearch
   replicas: 3
   selector:
      matchLabels:
          app: elasticsearch
          node: master
   template:
     metadata:
             labels:
              app: elasticsearch
              node: master
     spec:
      initContainers:
      - name: fix-the-volume-permission
        image: busybox
        command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-the-vm-max-map-count
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: increase-the-ulimit
        image: busybox
        command:
        - sh
        - -c
        - ulimit -n 65536
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.2
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: tcp
        resources:
          requests:
                  cpu: 100m
          limits:
                  cpu: 100m
        volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: elasticsearch-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: node.master
            value: "true"
          - name: node.data
            value: "false"
          - name: node.ingest
            value: "false"
          - name: network.host
            value: "_site_,_lo_"
          - name: discovery.seed_hosts
            value: "elasticsearch"
          - name: cluster.initial_master_nodes
            value: "master-es-0,master-es-1,master-es-2"
          - name: ES_JAVA_OPTS
            value: "-Xms256m -Xmx256m"
      affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                   matchExpressions:
                          - key: "node"
                            operator: In
                            values: 
                                - master
              topologyKey: "kubernetes.io/hostname"
   volumeClaimTemplates:
   - metadata:
      name: data
     spec:
       accessModes:
        - ReadWriteOnce
       storageClassName: ssd
       resources:
         requests:
           storage: 3Gi

